---
title: R for Data Science
---

### Logistics
| Person | Role | Contact |
|---|---|---|
| Alejandro Schuler | Instructor | alejandro.schuler@berkeley.edu |

- Website: [https://alejandroschuler.github.io/r4ds-courses/](https://alejandroschuler.github.io/r4ds-courses/)
- Source: [https://github.com/alejandroschuler/r4ds-courses](https://github.com/alejandroschuler/r4ds-courses)

### Overview
This course will make you an expert at data I/O, transformation, programming, and visualization in R. 
We will use a consistent set of packages for these tasks called the `tidyverse`.

This is not a traditional programming or computer science course. 
It is meant to be an *applied* tour of how to actually use R for your data science needs. 
We also will not cover statistical analysis of data in this course, but the curriculum is a useful prerequisite for subsequent courses on statistics or machine learning.

This course is not graded, nor are there any assignments or homework. The lectures are just to get you started- they will be frequently interrupted by active learning exercises that you will be asked to complete in pairs or small groups. That's where the real learning will happen!

### Prerequisites
No prior experience with R is expected. Those with experience using R will still likely find much of value in this course since it covers a more modern style of R programming that has gained traction in the past decade.

We will use R through the RStudio interface. The easiest way to access RStudio is through the cloud: [posit.cloud](https://posit.cloud). It's fast and easy- just go the link, click "get started" and create an account. Once you're in, click "new project" near the upper-right and the RStudio interface will open.

Alternatively, you can install R and RStudio on your own computer: 
[Follow this link](https://cran.rstudio.com/) and click on the appropriate options for your operating system to install R, 
then do the same to [install RStudio](https://posit.co/download/rstudio-desktop/#download).

### Learning Goals
By the end of the course, you will be able to:

* comfortably use R through the Rstudio interface
* read and write tabular data between R and flat files
* subset, transform, summarize, join, and plot data
* write reusable and readable programs
* seek out, learn, and integrate new packages and code into your analyses

### Textbook
I recommend the fantastic book [R for Data Science](https://r4ds.hadley.nz/) (R4DS:2e) by [Hadley Wickham](http://hadley.nz/), Mine Çetinkaya-Rundel, and Garrett Grolemund (O'Reilly Media, 2017); it is online and also available in hardcopy. In the schedule below I have mapped the book chapters to the modules in the course if you want to do your own reading.

### Schedule and Slides

<table>
  <tbody>
    <tr>
        <th>Module</th>
        <th>Topic</th>
        <th>Learning Goals</th>
        <th>Packages</th>
        <th>Reading</th>
    </tr>
    <tr>
        <td>1</td>
        <td>[Intro and Plotting](lectures/1-intro-plotting.html)</td>
        <td><ul>
              <li>issue commands to R using the Rstudio REPL interface</li>
              <li>load a package into R</li>
              <li>read some tabluar data into R</li>
              <li>visualize tabluar data using ggplot geoms, aesthetics, and facets</li>
        </ul></td>
        <td><ul>
            <li><code>ggplot2</code></li>
        </ul></td>
        <td>R4DS ch. 1, 9-11</td>
    </tr>
    <tr>
      <td>2</td>
      <td>[R Programming](lectures/2-r-basics.html)</td>
      <td>
        <ul>
            <li>save values to variables</li>
            <li>find and call R functions with multiple arguments by position and name</li>
            <li>recognize and index vectors and lists</li>
            <li>recognize, import, and inspect data frames</li>
            <li>issue commands to R using the Rstudio script pane</li>
        </ul></td>
        <td><ul>
            <li><code>tibble</code></li>
            <li><code>readr</code></li>
        </ul></td>
        <td>R4DS ch. 2, 4, 6, 8, 20</td>
    </tr>
    <tr>
      <td>3</td>
      <td>[Tabluar Data](lectures/3-data-transformation.html)</td>
        <td><ul>
            <li>filter rows of a dataset based on conditions</li>
            <li>arrange rows of a dataset based on one or more columns</li>
            <li>select columns of a dataset</li>
            <li>mutate existing columns to create new columns</li>
            <li>use the pipe to combine multiple operations</li>          
        </ul></td>
        <td><ul>
            <li><code>dplyr</code></li>
        </ul></td>
        <td>R4DS ch. 3, 12-16, 18</td>
    </tr>
    <tr>
      <td>4</td>
      <td>[Advanced Tabular Data](lectures/4-adv-tabular-data.html)</td>
      <td>
        <ul>
            <li>group and summarize data by one or more columns</li>
            <li>transform between long and wide data formats</li>
            <li>combine multiple data frames using joins on one or more columns</li>
        </ul></td>
        <td><ul>
            <li><code>dplyr</code></li>
            <li><code>tidyr</code></li>
        </ul></td>
        <td>R4DS ch. 3, 5, 19 </td>
    </tr>
    <tr>
      <td>5</td>
      <td>[Functional Programming](lectures/5-functional-programming.html)</td>
        <td><ul>
            <li>write your own functions</li>
            <li>iterate functions over lists of arguments</li>
        </ul></td>
        <td><ul>
            <li><code>purrr</code></li>
        </ul></td>
        <td>R4DS ch. 25, 26</td>
    </tr>
  </tbody>
</table>

### Optional Practice Exercises

These notebooks are optional. Each one walks through a short analysis of NHANES data, the same survey the lectures draw on, and leaves gaps for you to fill in. Look for the ellipses (`...`) with a `TODO` comment above them. An answer key is posted next to each exercise.

| Module | Exercise | Answers |
|---|---|---|
| 1 | [Programming Basics](practice/p1_programming_basics.Rmd) | [answer key](practice/p1_programming_basics_answers.Rmd) |
| 2 | [R Fundamentals](practice/p2_R_fundamentals.Rmd) | [answer key](practice/p2_R_fundamentals_answers.Rmd) |
| 3 | [Basic Tabular Manipulation](practice/p3_basic_tabular_manipulation.Rmd) | [answer key](practice/p3_basic_tabular_manipulation_answers.Rmd) |
| 4 | [Advanced Tabular Data](practice/p4_adv_tabular_data.Rmd) | [answer key](practice/p4_adv_tabular_data_answers.Rmd) |
| 5 | [Functional Programming](practice/p5_functional_programming.Rmd) | [answer key](practice/p5_functional_programming_answers.Rmd) |
| extra | [Datatypes and I/O](practice/extra_demo_datatypes.Rmd) | worked example, nothing to fill in |

#### Downloading the files

Every notebook reads its data from a folder called `data` that has to sit right next to the notebook, so saving the `.Rmd` by itself will not be enough. The quickest way to get everything into the right places is to paste this into the R console and hit enter:

```r
dir.create("practice/data", recursive = TRUE)
base = "https://alejandroschuler.github.io/r4ds-courses/practice/"

for (f in c("p1_programming_basics.Rmd",
            "p2_R_fundamentals.Rmd",
            "p3_basic_tabular_manipulation.Rmd",
            "p4_adv_tabular_data.Rmd",
            "p5_functional_programming.Rmd",
            "extra_demo_datatypes.Rmd")) {
  download.file(paste0(base, f), file.path("practice", f), mode = "wb")
}

for (f in c("participants.csv", "exams.csv", "medications.csv", "state_health.csv")) {
  download.file(paste0(base, "data/", f), file.path("practice/data", f), mode = "wb")
}
```

This behaves the same way on posit.cloud as it does on your own computer. It makes a `practice` folder inside your working directory, drops the six notebooks into it, and puts the four data tables in `practice/data`. If you want the answer keys on hand too, add `_answers` before the `.Rmd` in any of the file names above and run it again.

To download by hand instead, click the links in the table and the notebook will save straight to your computer. You still need the four data tables: [participants.csv](practice/data/participants.csv), [exams.csv](practice/data/exams.csv), [medications.csv](practice/data/medications.csv), and [state_health.csv](practice/data/state_health.csv). Your browser opens those in a tab rather than saving them, so right-click each one and choose "Save link as". Put all four in a folder named `data` next to the notebooks.

On posit.cloud, the Upload button in the Files pane moves files from your computer into your project.

#### Opening and running a notebook

Look in the Files pane at the lower right of RStudio, click into the `practice` folder, and click a notebook. It opens in the editor as text and gray code chunks mixed together. Run one chunk at a time with the green triangle at its upper right. The Knit button above the editor runs everything from top to bottom and produces an HTML report.

The exercises need a few packages you may not have yet. Install them once with:

```r
install.packages(c("tidyverse", "maps"))
```

